language: python

python:
  - "3.7"
  - "pypy3"

sudo: false

install:
  - pip install -r requirements-dev.txt
  - pip install tox-travis
  - pip install coveralls

before_script:
  - flake8 --max-line-length=120 .

script:
  - tox

after_success:
  - coveralls
