language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 3.5.1
    - os: osx
      osx_image: xcode7.3
      python: 3.5.1

before_install:
    - bash .ci/deps.${TRAVIS_OS_NAME}.sh

install:
  - pip install tox

script:
  - tox
