language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 3.5.1
    - os: osx
      osx_image: xcode7.3
      python: 3.5.1

before_install:
    - brew update
    - brew outdated python3 || brew upgrade python3

install:
  - pip install tox

script:
  - tox
